.enum Lattice = {
    case "Top",
    case "Neg", case "Pos",
    case "Bot"
}
.def glb (a: Lattice, b: Lattice): Lattice {
    case ("Bot", _) => "Bot",
    case (_, "Bot") => "Bot",
    case (_, _) => a = b ? a : "Top"
}
.def lub (a: Lattice, b: Lattice): Lattice {
    case ("Top", _) => "Top",
    case (_, "Top") => "Top",
    case (_, _) => a = b ? a : "Bot"
}
.let Lattice<> = ("Bot", "Top", lub, glb)

.lat a(x:number, l:Lattice)
.output a

a(1, "Bot").
a(1, "Top").
